//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Директор отдела по работе с клиентами.
    /// </summary>
    // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами CustomAttributes)

    // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами CustomAttributes)
    [AutoAltered()]
    [Caption("Директор отдела по работе с клиентами")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДиректорОтделаПоРаботеСКлиентамиE", new string[] {
            "id as \'Id\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТел as \'Номер тел\'",
            "СерияПаспорта as \'Серия паспорта\'",
            "НомерПаспорта as \'Номер паспорта\'"})]
    [View("ДиректорОтделаПоРаботеСКлиентамиL", new string[] {
            "id as \'Id\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТел as \'Номер тел\'",
            "СерияПаспорта as \'Серия паспорта\'",
            "НомерПаспорта as \'Номер паспорта\'"})]
    public class ДиректорОтделаПоРаботеСКлиентами : ICSSoft.STORMNET.DataObject
    {
        
        private string fid;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private string fНомерТел;
        
        private string fСерияПаспорта;
        
        private string fНомерПаспорта;
        
        // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами CustomMembers)

        // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами CustomMembers)

        
        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id CustomAttributes)

        // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id CustomAttributes)
        [StrLen(255)]
        public virtual string id
        {
            get
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id Get start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id Get start)
                string result = this.fid;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id Get end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id Set start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id Set end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.id Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя CustomAttributes)

        // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя Get start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя Get end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя Set start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя Set end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Имя Set end)
            }
        }
        
        /// <summary>
        /// НомерПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта CustomAttributes)

        // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта CustomAttributes)
        [StrLen(255)]
        public virtual string НомерПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта Get start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта Get start)
                string result = this.fНомерПаспорта;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта Get end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта Set start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта Set start)
                this.fНомерПаспорта = value;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта Set end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерПаспорта Set end)
            }
        }
        
        /// <summary>
        /// НомерТел.
        /// </summary>
        // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел CustomAttributes)

        // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел CustomAttributes)
        [StrLen(255)]
        public virtual string НомерТел
        {
            get
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел Get start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел Get start)
                string result = this.fНомерТел;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел Get end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел Set start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел Set start)
                this.fНомерТел = value;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел Set end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.НомерТел Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество CustomAttributes)

        // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество Get start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество Get end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество Set start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество Set end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Отчество Set end)
            }
        }
        
        /// <summary>
        /// СерияПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта CustomAttributes)

        // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта CustomAttributes)
        [StrLen(255)]
        public virtual string СерияПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта Get start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта Get start)
                string result = this.fСерияПаспорта;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта Get end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта Set start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта Set start)
                this.fСерияПаспорта = value;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта Set end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.СерияПаспорта Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия CustomAttributes)

        // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия Get start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия Get end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия Set start)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия Set end)

                // *** End programmer edit section *** (ДиректорОтделаПоРаботеСКлиентами.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДиректорОтделаПоРаботеСКлиентамиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДиректорОтделаПоРаботеСКлиентамиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДиректорОтделаПоРаботеСКлиентамиE", typeof(IIS.Kursovaya8.ДиректорОтделаПоРаботеСКлиентами));
                }
            }
            
            /// <summary>
            /// "ДиректорОтделаПоРаботеСКлиентамиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДиректорОтделаПоРаботеСКлиентамиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДиректорОтделаПоРаботеСКлиентамиL", typeof(IIS.Kursovaya8.ДиректорОтделаПоРаботеСКлиентами));
                }
            }
        }
    }
}
