//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заключение договора.
    /// </summary>
    // *** Start programmer edit section *** (ЗаключениеДоговора CustomAttributes)

    // *** End programmer edit section *** (ЗаключениеДоговора CustomAttributes)
    [AutoAltered()]
    [Caption("Заключение договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаключениеДоговораE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Стоимость as \'Стоимость\'"})]
    [View("ЗаключениеДоговораL", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Стоимость as \'Стоимость\'"})]
    public class ЗаключениеДоговора : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private IIS.Kursovaya8.ТипДоговора fТип;
        
        private int fСтоимость;
        
        private IIS.Kursovaya8.ДиректорОтделаПоРаботеСКлиентами fДиректорОтделаПоРаботеСКлиентами;
        
        private IIS.Kursovaya8.ОказаниеКонсультаций fОказаниеКонсультаций;
        
        private IIS.Kursovaya8.Клиент fКлиент;
        
        // *** Start programmer edit section *** (ЗаключениеДоговора CustomMembers)

        // *** End programmer edit section *** (ЗаключениеДоговора CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Дата Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Дата Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Дата Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Дата Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Номер CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Номер Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Номер Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Номер Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Номер Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Номер Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Стоимость Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Тип CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Тип CustomAttributes)
        public virtual IIS.Kursovaya8.ТипДоговора Тип
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Тип Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Тип Get start)
                IIS.Kursovaya8.ТипДоговора result = this.fТип;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Тип Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Тип Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Тип Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Тип Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами CustomAttributes)
        [PropertyStorage(new string[] {
                "ДиректорОтделаПоРаботеСКлиентами"})]
        [NotNull()]
        public virtual IIS.Kursovaya8.ДиректорОтделаПоРаботеСКлиентами ДиректорОтделаПоРаботеСКлиентами
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get start)
                IIS.Kursovaya8.ДиректорОтделаПоРаботеСКлиентами result = this.fДиректорОтделаПоРаботеСКлиентами;
                // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set start)
                this.fДиректорОтделаПоРаботеСКлиентами = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Kursovaya8.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Клиент Get start)
                IIS.Kursovaya8.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.Клиент Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций CustomAttributes)

        // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций CustomAttributes)
        [PropertyStorage(new string[] {
                "ОказаниеКонсультаций"})]
        [NotNull()]
        public virtual IIS.Kursovaya8.ОказаниеКонсультаций ОказаниеКонсультаций
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Get start)

                // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Get start)
                IIS.Kursovaya8.ОказаниеКонсультаций result = this.fОказаниеКонсультаций;
                // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Get end)

                // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Set start)

                // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Set start)
                this.fОказаниеКонсультаций = value;
                // *** Start programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Set end)

                // *** End programmer edit section *** (ЗаключениеДоговора.ОказаниеКонсультаций Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаключениеДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаключениеДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаключениеДоговораE", typeof(IIS.Kursovaya8.ЗаключениеДоговора));
                }
            }
            
            /// <summary>
            /// "ЗаключениеДоговораL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаключениеДоговораL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаключениеДоговораL", typeof(IIS.Kursovaya8.ЗаключениеДоговора));
                }
            }
        }
    }
}
