//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оказание консультаций.
    /// </summary>
    // *** Start programmer edit section *** (ОказаниеКонсультаций CustomAttributes)

    // *** End programmer edit section *** (ОказаниеКонсультаций CustomAttributes)
    [AutoAltered()]
    [Caption("Оказание консультаций")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОказаниеКонсультацийE", new string[] {
            "Дата as \'Дата\'",
            "ВремяКонсультации as \'Время консультации\'",
            "ПредоставленнаяУслуга as \'Предоставленная услуга\'"})]
    [View("ОказаниеКонсультацийL", new string[] {
            "Дата as \'Дата\'",
            "ВремяКонсультации as \'Время консультации\'",
            "ПредоставленнаяУслуга as \'Предоставленная услуга\'"})]
    public class ОказаниеКонсультаций : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fВремяКонсультации;
        
        private IIS.Kursovaya8.Услуга fПредоставленнаяУслуга;
        
        private IIS.Kursovaya8.РасчетОставшегосяВремени fРасчетОставшегосяВремени;
        
        // *** Start programmer edit section *** (ОказаниеКонсультаций CustomMembers)

        // *** End programmer edit section *** (ОказаниеКонсультаций CustomMembers)

        
        /// <summary>
        /// ВремяКонсультации.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации CustomAttributes)
        public virtual int ВремяКонсультации
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Get start)
                int result = this.fВремяКонсультации;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Set start)
                this.fВремяКонсультации = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПредоставленнаяУслуга.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга CustomAttributes)
        public virtual IIS.Kursovaya8.Услуга ПредоставленнаяУслуга
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Get start)
                IIS.Kursovaya8.Услуга result = this.fПредоставленнаяУслуга;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Set start)
                this.fПредоставленнаяУслуга = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya8.РасчетОставшегосяВремени.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетОставшегосяВремени"})]
        public virtual IIS.Kursovaya8.РасчетОставшегосяВремени РасчетОставшегосяВремени
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Get start)
                IIS.Kursovaya8.РасчетОставшегосяВремени result = this.fРасчетОставшегосяВремени;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Set start)
                this.fРасчетОставшегосяВремени = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОказаниеКонсультацийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОказаниеКонсультацийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОказаниеКонсультацийE", typeof(IIS.Kursovaya8.ОказаниеКонсультаций));
                }
            }
            
            /// <summary>
            /// "ОказаниеКонсультацийL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОказаниеКонсультацийL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОказаниеКонсультацийL", typeof(IIS.Kursovaya8.ОказаниеКонсультаций));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОказаниеКонсультаций.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОказаниеКонсультаций CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОказаниеКонсультаций CustomAttributes)
    public class DetailArrayOfОказаниеКонсультаций : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya8.DetailArrayOfОказаниеКонсультаций members)

        // *** End programmer edit section *** (IIS.Kursovaya8.DetailArrayOfОказаниеКонсультаций members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОказаниеКонсультаций by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОказаниеКонсультаций.
        /// </summary>
        public DetailArrayOfОказаниеКонсультаций(IIS.Kursovaya8.РасчетОставшегосяВремени fРасчетОставшегосяВремени) : 
                base(typeof(ОказаниеКонсультаций), ((ICSSoft.STORMNET.DataObject)(fРасчетОставшегосяВремени)))
        {
        }
        
        public IIS.Kursovaya8.ОказаниеКонсультаций this[int index]
        {
            get
            {
                return ((IIS.Kursovaya8.ОказаниеКонсультаций)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya8.ОказаниеКонсультаций dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
