//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расторжение договора.
    /// </summary>
    // *** Start programmer edit section *** (РасторжениеДоговора CustomAttributes)

    // *** End programmer edit section *** (РасторжениеДоговора CustomAttributes)
    [AutoAltered()]
    [Caption("Расторжение договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасторжениеДоговораE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'"})]
    [View("РасторжениеДоговораL", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'"})]
    public class РасторжениеДоговора : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private IIS.Kursovaya8.Клиент fКлиент;
        
        private IIS.Kursovaya8.ДиректорОтделаПоРаботеСКлиентами fДиректорОтделаПоРаботеСКлиентами;
        
        // *** Start programmer edit section *** (РасторжениеДоговора CustomMembers)

        // *** End programmer edit section *** (РасторжениеДоговора CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасторжениеДоговора.Дата CustomAttributes)

        // *** End programmer edit section *** (РасторжениеДоговора.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Дата Get start)

                // *** End programmer edit section *** (РасторжениеДоговора.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасторжениеДоговора.Дата Get end)

                // *** End programmer edit section *** (РасторжениеДоговора.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Дата Set start)

                // *** End programmer edit section *** (РасторжениеДоговора.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасторжениеДоговора.Дата Set end)

                // *** End programmer edit section *** (РасторжениеДоговора.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (РасторжениеДоговора.Номер CustomAttributes)

        // *** End programmer edit section *** (РасторжениеДоговора.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Номер Get start)

                // *** End programmer edit section *** (РасторжениеДоговора.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (РасторжениеДоговора.Номер Get end)

                // *** End programmer edit section *** (РасторжениеДоговора.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Номер Set start)

                // *** End programmer edit section *** (РасторжениеДоговора.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (РасторжениеДоговора.Номер Set end)

                // *** End programmer edit section *** (РасторжениеДоговора.Номер Set end)
            }
        }
        
        /// <summary>
        /// Расторжение договора.
        /// </summary>
        // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами CustomAttributes)

        // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами CustomAttributes)
        [PropertyStorage(new string[] {
                "ДиректорОтделаПоРаботеСКлиентами"})]
        [NotNull()]
        public virtual IIS.Kursovaya8.ДиректорОтделаПоРаботеСКлиентами ДиректорОтделаПоРаботеСКлиентами
        {
            get
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get start)

                // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get start)
                IIS.Kursovaya8.ДиректорОтделаПоРаботеСКлиентами result = this.fДиректорОтделаПоРаботеСКлиентами;
                // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get end)

                // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set start)

                // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set start)
                this.fДиректорОтделаПоРаботеСКлиентами = value;
                // *** Start programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set end)

                // *** End programmer edit section *** (РасторжениеДоговора.ДиректорОтделаПоРаботеСКлиентами Set end)
            }
        }
        
        /// <summary>
        /// Расторжение договора.
        /// </summary>
        // *** Start programmer edit section *** (РасторжениеДоговора.Клиент CustomAttributes)

        // *** End programmer edit section *** (РасторжениеДоговора.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Kursovaya8.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Клиент Get start)

                // *** End programmer edit section *** (РасторжениеДоговора.Клиент Get start)
                IIS.Kursovaya8.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (РасторжениеДоговора.Клиент Get end)

                // *** End programmer edit section *** (РасторжениеДоговора.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасторжениеДоговора.Клиент Set start)

                // *** End programmer edit section *** (РасторжениеДоговора.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (РасторжениеДоговора.Клиент Set end)

                // *** End programmer edit section *** (РасторжениеДоговора.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасторжениеДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасторжениеДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасторжениеДоговораE", typeof(IIS.Kursovaya8.РасторжениеДоговора));
                }
            }
            
            /// <summary>
            /// "РасторжениеДоговораL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасторжениеДоговораL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасторжениеДоговораL", typeof(IIS.Kursovaya8.РасторжениеДоговора));
                }
            }
        }
    }
}
