//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya8
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуга.
    /// </summary>
    // *** Start programmer edit section *** (Услуга CustomAttributes)

    // *** End programmer edit section *** (Услуга CustomAttributes)
    public enum Услуга
    {
        
        // *** Start programmer edit section *** (Услуга.ПомощьВПроведенииДокумента CustomAttributes)

        // *** End programmer edit section *** (Услуга.ПомощьВПроведенииДокумента CustomAttributes)
        ПомощьВПроведенииДокумента,
        
        // *** Start programmer edit section *** (Услуга.ПомощьВЗакрытииМесяца CustomAttributes)

        // *** End programmer edit section *** (Услуга.ПомощьВЗакрытииМесяца CustomAttributes)
        ПомощьВЗакрытииМесяца,
        
        // *** Start programmer edit section *** (Услуга.РешениеУстногоВопроса CustomAttributes)

        // *** End programmer edit section *** (Услуга.РешениеУстногоВопроса CustomAttributes)
        РешениеУстногоВопроса,
    }
}
